/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author adept
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    //to fetch the issue book details from the database and display it to panel
    public void getIssueBookDetails()
    {
        int bookId = Integer.parseInt(txt_bookId.getText());
        int diffDay;
        int studentId = Integer.parseInt(txt_studentId.getText());
        try
        {
            java.sql.Connection con = DBConnection.getConnection();
            String sql = "select *from issue_book_details where book_id = ? and student_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,bookId);
            pst.setInt(2,studentId);
            pst.setString(3,"pending");
           java.sql.ResultSet rs = pst.executeQuery();
           if(rs.next())
           {
               lbl_issueId.setText(rs.getString("id"));
               lbl_bookName.setText(rs.getString("book_name"));
               lbl_studentName.setText(rs.getString("student_name"));
               lbl_issueDate.setText(rs.getString("issue_date"));
               lbl_dueDate.setText(rs.getString("due_date"));
               Date d1 = new Date();
               Date d2 = rs.getDate("due_date");    
               long d1_Time = d1.getTime();
               long d2_Time = d2.getTime();
               if(d1_Time >= d2_Time)
               {
                   diffDay = (int)((d1_Time - d2_Time)/(1000*60*60*24))%365;
                   lbl_dayLate.setText(Integer.toString(diffDay)+" Day Late");
               }   
               else
                   lbl_dayLate.setText("No Late");
               lbl_bookError.setText("");
            }else
           {
               lbl_issueId.setText("");
               lbl_bookName.setText("");
               lbl_studentName.setText("");
               lbl_issueDate.setText("");
               lbl_dueDate.setText("");
               lbl_bookError.setText("No Record Found");
           }
        }catch(Exception e)
        {
            e.printStackTrace();
        }    
    }
   //return book 
    public boolean returnBook()
    {
        boolean isReturned = false;
        int bookId = Integer.parseInt(txt_bookId.getText());
        int studentId = Integer.parseInt(txt_studentId.getText());
        try
        {
            java.sql.Connection con = DBConnection.getConnection();
            String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,"returned");
            pst.setInt(2,studentId);
            pst.setInt(3,bookId);
            pst.setString(4,"pending");
            int rowCount = pst.executeUpdate();
            if(rowCount>0)
               isReturned = true;
            else
                isReturned = false;
        }catch(Exception e)
        {
            e.printStackTrace();
        }  
        return isReturned;
    }
   //updating book count
    public void updateBookCount()
    {      
          int bookId = Integer.parseInt(txt_bookId.getText());
          try
          {
           java.sql.Connection con = DBConnection.getConnection();
           String sql = "update book_details set quantity = quantity + 1 where book_id = ?";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setInt(1,bookId);
           int rowCount = pst.executeUpdate();
           if(rowCount > 0)
               JOptionPane.showMessageDialog(this,"Book count updated");   
            else
               JOptionPane.showMessageDialog(this,"Can't update book count");
          }catch(Exception e)
          {
              e.printStackTrace();
          }   
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Main = new javax.swing.JPanel();
        panel_bookDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_issueId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_studentName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_bookError = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_dueDate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_dayLate = new javax.swing.JLabel();
        panel_returnBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_studentId = new app.bolivia.swing.JCTextField();
        button_returnBook = new rojerusan.RSMaterialButtonCircle();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        button_findDetails = new rojerusan.RSMaterialButtonCircle();
        panel_image = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Main.setBackground(new java.awt.Color(255, 255, 255));
        panel_Main.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 0)));
        panel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_bookDetails.setBackground(new java.awt.Color(204, 51, 0));
        panel_bookDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel1.setText(" Book Details");
        panel_bookDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, 100));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        panel_bookDetails.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Issue Date :");
        panel_bookDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, -1));

        lbl_issueDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 210, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Book Name :");
        panel_bookDetails.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Name :");
        panel_bookDetails.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, -1));

        lbl_issueId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_issueId.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, 40));

        lbl_bookName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 210, 40));

        lbl_studentName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_studentName.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 210, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Due Date :");
        panel_bookDetails.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, -1));

        lbl_bookError.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_bookError.setForeground(new java.awt.Color(204, 204, 204));
        panel_bookDetails.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 210, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Issue Id :");
        panel_bookDetails.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, -1));

        lbl_dueDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_dueDate.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 210, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Day Late :");
        panel_bookDetails.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, -1));

        lbl_dayLate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbl_dayLate.setForeground(new java.awt.Color(255, 255, 255));
        panel_bookDetails.add(lbl_dayLate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 210, 40));

        panel_Main.add(panel_bookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 2, 370, 646));

        panel_returnBook.setBackground(new java.awt.Color(255, 255, 255));
        panel_returnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel3.setText("Return Book");
        panel_returnBook.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        panel_returnBook.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Book Id :");
        panel_returnBook.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, -1));

        txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_bookId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_bookId.setPlaceholder("Enter Book Id...");
        panel_returnBook.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 210, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Student Id :");
        panel_returnBook.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, -1));

        txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_studentId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_studentId.setPlaceholder("Enter Student Id...");
        panel_returnBook.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, -1));

        button_returnBook.setBackground(new java.awt.Color(255, 51, 51));
        button_returnBook.setText("Return Book");
        button_returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_returnBookActionPerformed(evt);
            }
        });
        panel_returnBook.add(button_returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 290, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(225, 51, 51));
        jLabel18.setText("X");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        panel_returnBook.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 62, -1));

        button_findDetails.setBackground(new java.awt.Color(153, 102, 255));
        button_findDetails.setText("FIND DETAILS");
        button_findDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_findDetailsActionPerformed(evt);
            }
        });
        panel_returnBook.add(button_findDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 290, 60));

        panel_Main.add(panel_returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 2, 391, 646));

        panel_image.setBackground(new java.awt.Color(255, 255, 255));
        panel_image.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_image.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 35));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/library-2.png"))); // NOI18N
        panel_image.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 37, 485, 648));
        jLabel16.getAccessibleContext().setAccessibleName("");

        panel_Main.add(panel_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 485, 646));
        panel_image.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 650));

        setSize(new java.awt.Dimension(1250, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        Color mouseEnterColor1 = new Color(255,51,51);
        jPanel4.setBackground(mouseEnterColor1);
        Color mouseEnterColor2 = new Color(255,255,255);
        jLabel18.setForeground(mouseEnterColor2);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        Color mouseExitColor1 = new Color(255,255,255);
        jPanel4.setBackground(mouseExitColor1);
        Color mouseExitColor2 = new Color(255,51,51);
        jLabel18.setForeground(mouseExitColor2);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        Color mouseEnterColor = new Color(255,51,51);
        jPanel3.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        Color mouseExitColor = new Color(255,204,204);
        jPanel3.setBackground(mouseExitColor);
    }//GEN-LAST:event_jPanel3MouseExited

    private void button_returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_returnBookActionPerformed
        getIssueBookDetails();
        if(returnBook() == true)
         {   
             JOptionPane.showMessageDialog(this,"Book Return Successfully");
             updateBookCount();
         }    
         else
                 JOptionPane.showMessageDialog(this,"Book Return Failed");
    }//GEN-LAST:event_button_returnBookActionPerformed

    private void button_findDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_findDetailsActionPerformed
        getIssueBookDetails();
    }//GEN-LAST:event_button_findDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle button_findDetails;
    private rojerusan.RSMaterialButtonCircle button_returnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_bookError;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dayLate;
    private javax.swing.JLabel lbl_dueDate;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_issueId;
    private javax.swing.JLabel lbl_studentName;
    private javax.swing.JPanel panel_Main;
    private javax.swing.JPanel panel_bookDetails;
    private javax.swing.JPanel panel_image;
    private javax.swing.JPanel panel_returnBook;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_studentId;
    // End of variables declaration//GEN-END:variables
}
